# This is a basic workflow to help you get started with Actions

name: dependent jobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print Build Message
        run: echo Building application...

      # Runs a set of commands using the runners shell
      - name: Simulate Build
        run: 
          echo Simulating sleep
          sleep 10
          echo Build complete!

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Makes 'test' depend on 'build'
    needs: build 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print Running test Message
        run: echo Running tests...

      # Runs a set of commands using the runners shell
      - name: Simulate Testing
        run: 
          echo Simulating testing
          sleep 10
          echo Testing complete!
          
          

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Makes 'test' depend on 'build'
    needs: test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print Running Deploy Message
        run: echo Deploying application...

      # Runs a set of commands using the runners shell
      - name: Simulate Deployment
        run: 
          echo Simulating deployment
          sleep 10
          echo Deployment complete!
          echo Add other actions to build,
          echo test, and deploy your project.
