name: Proper use of variables (secrets, tokens and environment variables)

on: push

jobs:
  deplo-staging:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CONTAINER_NAME: docker-container-for-staging
    
    steps:
      - uses: actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}